#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:
  orderer.cbbc.lt:
    container_name: orderer.cbbc.lt
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /etc/hyperledger
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/cbbc.lt/orderers/orderer.cbbc.lt/:/etc/hyperledger/msp/orderer
        - ./crypto-config/peerOrganizations/manufacturer.cbbc.lt/peers/peer0.manufacturer.cbbc.lt/:/etc/hyperledger/msp/peerManufacturer
        - ./crypto-config/peerOrganizations/retailer.cbbc.lt/peers/peer0.retailer.cbbc.lt/:/etc/hyperledger/msp/peerRetailer
        - ./crypto-config/peerOrganizations/expeditor.cbbc.lt/peers/peer0.expeditor.cbbc.lt/:/etc/hyperledger/msp/peerExpeditor
        - ./crypto-config/peerOrganizations/auditor.cbbc.lt/peers/peer0.auditor.cbbc.lt/:/etc/hyperledger/msp/peerAuditor
    networks:
      - basic

  peer0.manufacturer.cbbc.lt:
    container_name: peer0.manufacturer.cbbc.lt
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.manufacturer.cbbc.lt
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=ManufacturerMsp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.manufacturer.cbbc.lt:7051
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/peer/ca.crt
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /etc/hyperledger
    command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/ordererOrganizations/cbbc.lt:/etc/hyperledger/orderer
        - ./crypto-config/peerOrganizations/manufacturer.cbbc.lt/peers/peer0.manufacturer.cbbc.lt/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/manufacturer.cbbc.lt/peers/peer0.manufacturer.cbbc.lt/tls:/etc/hyperledger/tls/peer
        - ./crypto-config/peerOrganizations/manufacturer.cbbc.lt/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.cbbc.lt
      - couchdb
    networks:
      - basic

  peer0.retailer.cbbc.lt:
    container_name: peer0.retailer.cbbc.lt
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.retailer.cbbc.lt
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=RetailerMsp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.retailer.cbbc.lt:7151
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-chaincodedev=true
    ports:
      - 7151:7151
      - 7153:7153
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/retailer.cbbc.lt/peers/peer0.retailer.cbbc.lt/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/retailer.cbbc.lt/users:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.cbbc.lt
      - couchdb
    networks:
      - basic

  peer0.expeditor.cbbc.lt:
    container_name: peer0.expeditor.cbbc.lt
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.expeditor.cbbc.lt
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=ExpeditorMsp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.expeditor.cbbc.lt:7251
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-chaincodedev=true
    ports:
      - 7251:7251
      - 7253:7253
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/expeditor.cbbc.lt/peers/peer0.expeditor.cbbc.lt/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/expeditor.cbbc.lt/users:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.cbbc.lt
      - couchdb
    networks:
      - basic

  peer0.auditor.cbbc.lt:
    container_name: peer0.auditor.cbbc.lt
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.expeditor.cbbc.lt
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=AuditorMsp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.auditor.cbbc.lt:7351
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-chaincodedev=true
    ports:
      - 7351:7351
      - 7353:7353
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/auditor.cbbc.lt/peers/peer0.auditor.cbbc.lt/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/auditor.cbbc.lt/users:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.cbbc.lt
      - couchdb
    networks:
      - basic

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - basic
