#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=debug
      - CORE_PEER_ID=cli
      - CORE_PEER_LOCALMSPID=ManufacturerMsp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peerOrganizations/manufacturer.cbbc.lt/users/Admin@manufacturer.cbbc.lt/msp
      - CORE_PEER_ADDRESS=peer0.manufacturer.cbbc.lt:7051
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peerOrganizations/manufacturer.cbbc.lt/peers/peer0.manufacturer.cbbc.lt/tls/ca.crt
      - CORE_ORDERER_CA_FILE=/etc/hyperledger/crypto/ordererOrganizations/cbbc.lt/tlsca/tlsca.cbbc.lt-cert.pem
      - CORE_CHAINCODE_KEEPALIVE=20
    working_dir: /etc/hyperledger
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/
        - ./config:/etc/hyperledger/configtx/
        - ./crypto-config:/etc/hyperledger/crypto/
    networks:
        - basic
